### ISSUE TITLE
目前个人使用的DNS方案分享

### ISSUE THREAD

**Issue by luckyyyyy** [luckyyyyy/blog#71]
## 0x00 问题
其实这个问题很久了，之前做了很多分流，虽然抗污染能力增强，但是还是会出现一些污染的情况，目前来说最合理的方案依然是fake-ip，但我不希望所有国内地址都被解析成fake-ip，还有就是国内ip全部进clash内核这也是我不希望的。所以需要一份域名白名单来解决这个问题。

## 0x01 解决
DNS依然可以使用AdGuard Home来作为第一层服务器，主要是因为这家伙的UI做的我非常满意，而且重写，记录等功能也是我需要的。
### 端口 
AdGuard Home 监听 5553（选择挟持53端口，因为我希望这是第一站）
Clash 监听 1053
dnsmasq 监听 53（默认不变，防止其他服务器没启动连DNS都没有）

### AdGuard Home 的配置
现在可以使用我这个项目 https://github.com/luckyyyyy/GFWList2AGH 来做AdGuard Home的分流，把gfwlist2adguardhome/whitelist_full.txt 文件写到配置中即可，这个文件是china list 转发到 杭州电信的IP，如果希望是其他IP，请自行手动修改最后的IP或者转发给dnsmasq，dnsmasq自动使用pppoe拨号给的DNS（这个没问题的，国内的域名就应该用域名是的服务器解析，如果不信任，那就上游自己改吧）。

<img width="729" alt="image" src="https://github.com/luckyyyyy/blog/assets/9210430/2cc55ba9-8abc-4506-8723-e63c4b023295">

### clash配置
clash的配置我就不解释了，直接给出配置
```yaml
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:1053
  nameserver:
    - 127.0.0.1:53
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  default-nameserver:
    - 119.28.28.28
    - 223.5.5.5
    - 202.101.172.35
    - 202.101.172.47
  fake-ip-filter:
    - "*.lan"
  fallback-filter:
    geoip: true
    geoip-code: CN
```
